### ISSUE TITLE
Error when running bot

### ISSUE THREAD

**Issue by Fabatax** [joshuayuen99/TundraBot#14]
```
> tundrabot@2.0.0 start /home/ubuntu/TundraBot
> node dist/TundraBot.js

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'node:events'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/ubuntu/TundraBot/node_modules/discord.js/src/client/BaseClient.js:3:22)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tundrabot@2.0.0 start: `node dist/TundraBot.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tundrabot@2.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-12-07T04_47_28_481Z-debug.log
```
can someone help?

**Comment by joshuayuen99** [comment]
What version of Node are you using? This error can happen if you are using something before v16.6.

**Comment by danielclough** [comment]
I'm having this issue with node v16.13.1.

I found a workaround adding `"skipLibCheck": true,` to `ts-config.json`

**Comment by Fabatax** [comment]
Closing this issue because I don't remember what Node version I was using because I did a reinstall on my server and ran other stuff.
